# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=15)),
                ('gen', models.CharField(max_length=10)),
            ],
        ),
    ]
